pg_groups:
  ds:
    - "{{ zookeeper_ports['zk_data_port'] }}"
    - "{{ cassandra_ports['cassandra_cql_native_port'] }}"
    - "{{ cassandra_ports['cassandra_thrift_client_port'] }}"
  ms: 
    - "{{ ms_ext_mgmt_port }}"
  pg:
    - "{{ pg_db_port }}"
    - 22